language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-21

install:
  - echo y | sdkmanager 'ndk-bundle'

script:
   - cd ./VirtualApp
   - ./gradlew build

after_failure:
  - cat ./YAHFA/build/reports/lint-results.xml
  - cat ./app/build/reports/lint-results.xml
  - cat ./demoHookPlugin/build/reports/lint-results.xml
  - cat ./lib/build/reports/lint-results.xml
