language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-21

install:
  - echo y | sdkmanager 'ndk-bundle'

script:
   - cd ./VirtualApp
   - ./gradlew build
